services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER:-admin}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-changeme}
      POSTGRES_DB: ${DATABASE_NAME:-measurements_llm}
    volumes:
      - db_measurements:/var/lib/postgresql/data
volumes:
  db_measurements:
    driver: local
