services:
  server:
    build: .
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    environment:
      NODE_ENV: production
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      DATABASE_HOST: ${DATABASE_HOST:-db}
    depends_on:
      db:
        condition: service_started
        restart: true

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER:-admin}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-changeme}
      POSTGRES_DB: ${DATABASE_NAME:-measurements_llm}
    volumes:
      - db_measurements:/var/lib/postgresql/data
volumes:
  db_measurements:
    driver: local
